### ISSUE TITLE
Instructions are incomplete

### ISSUE THREAD

**Issue by citbr** [AhadCove/routeme#2]
Unfortunately your instructions are incomplete - you need to think like a user, not a programmer, when writing instructions.  This means don't assume any prior knowledge, don't skip any steps, and put commands on separate lines or enclose them in quotes or put them in boldface or whatever you need to do to avoid ambiguity with the surrounding text.

In particular, anyone reading your instructions that is not a programmer (and probably many programmers) would have no idea how to download and install your code on a Raspberry Pi (and if they hadn't come here from your article they might not even know that this was written to run on a Raspberry Pi).  You go right to setup instructions, with nary a word about how to install this thing.

And then you start with this sentence:

> First run yarn or npm i Rename config.example.js to config.js

Huh?  What, exactly, are you supposed to run, and from where?  And also, there is no program called yarn on my Raspberry Pi, but even if there were the sentence is so ambiguous that I have no idea what I'm actually supposed to be running here.

Seriously, you have to explain this stuff as if you were writing it for a fifth grader (of average intelligence), otherwise you will probably be the only one (or only one of a handful of people) that's ever able to install and use your program.

**Comment by Swell1** [comment]
Good points. 
This may help:  
https://medium.com/@ahadcove/bringing-back-google-maps-by-text-messaging-using-a-raspberry-pi-9ca51bc912df

**Comment by citbr** [comment]
Thanks, but I'd already seen that article.  It also doesn't explain how to install your program on a Raspberry Pi, nor does it address the ambiguity in the configuration instructions.

**Comment by emmeaboyoun1** [comment]
Yes, having difficulty understanding the instructions as well. Can you be more clear and explain the steps of the set up? I watched your youtube video for SMS but it does not explain how you got there. Thank you

**Comment by ahadcove** [comment]
Thank you for your input.
While in an ideal world this would take you from literally step one: Installing raspbian all the way to starting up routeme, you're not likely to see that on Github.

Github isn't really meant to be a place for "non coders".

Raspberry Pi isn't mentioned in the instructions because this program will work on any computer. In my article I just use it on my Raspberry Pi, but it could literally run from the computer you're using currently.

**Comment by citbr** [comment]
Two people tell you they are having trouble understanding your instructions.  Your response is, 'Github isn't really meant to be a place for "non coders".'  Which is not actually true because many developers use it to distribute their software, and unlike you don't expect all users of their software or Github to be coders.  But in any case, it seems you have a problem accepting constructive criticism, so I'll not bother with you or your software ever again.  Have fun developing for the three or four people who can actually understand what the hell you're doing.
